import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const html = await readFile("dist/sourcing-dashboard.html", "utf8");
const script = await readFile("dist/sourcing-dashboard.js", "utf8");
const worker = await readFile("dist/_worker.js", "utf8");

assert.match(html, /styles\.css\?v=20260610a/, "dashboard must load the latest daily bid report stylesheet version");
assert.match(html, /sourcing-dashboard\.js\?v=20260610a/, "dashboard must load the latest daily bid report script version");
assert.match(html, /<option selected>Whole UK<\/option>/, "dashboard must default contract search area to Whole UK");
assert.match(html, /id="opportunitySource"/, "dashboard must include the opportunity source selector");
assert.match(html, /Contracts Finder only/, "dashboard must expose Contracts Finder mode");
assert.match(html, /Goods contract matcher/, "dashboard must use contract-first wording");
assert.match(html, /Saved contract and tender opportunities/, "dashboard must save opportunities instead of buyer records");
assert.match(html, /Stock fulfilment agent/, "dashboard must rank stock against selected opportunities");
assert.match(html, /Most viable live opportunities/, "highlighted contract area must be the live opportunity board");
assert.match(html, /Run test-and-learn/, "dashboard must expose the full test-and-learn control");
assert.match(html, /Nationwide borough portals/, "dashboard must expose nationwide borough public-sector portal routes");
assert.match(html, /Continuous learning loop/, "dashboard must expose continuous learning wording");
assert.match(html, /Daily bid report/, "dashboard must expose the daily bid report panel");
assert.match(html, /id="modelHealth"/, "dashboard must expose model health panel");
assert.match(html, /id="sourceLearning"/, "dashboard must expose source learning panel");
assert.match(html, /id="routeLearning"/, "dashboard must expose route learning panel");
assert.match(html, /id="outcomeLearning"/, "dashboard must expose outcome learning panel");
assert.match(html, /id="importData"/, "dashboard must allow learning import");
assert.match(html, /Manual opportunity fallback/, "manual paste must be demoted to fallback workflow");
assert.match(html, /temporary accommodation appliances/, "dashboard must target startup-fit anchor contract keywords");
assert.match(html, /39700000/, "dashboard must include domestic appliance CPV targeting");

assert.match(script, /CONTRACTS_FINDER_SEARCH_BASE/, "front end must generate Contracts Finder search links");
assert.match(script, /PUBLIC_PROCUREMENT_SOURCES/, "front end must show government procurement source routes");
assert.match(script, /isUkWideRegion/, "front end must normalise UK-wide searches");
assert.match(script, /tenderQueryRegion/, "front end must avoid applying a local region filter to UK-wide searches");
assert.match(script, /East Midlands Tenders/, "front end must include East Midlands local authority portal routes");
assert.match(script, /Leicester City Council procurement/, "front end must include Leicester City Council procurement routes");
assert.match(script, /Leicestershire County Council procurement/, "front end must include Leicestershire County Council procurement routes");
assert.match(script, /Blaby District Council procurement/, "front end must include borough procurement routes");
assert.match(script, /LOCAL_AUTHORITY_SWEEP/, "front end must run a focused local-authority buyer sweep");
assert.match(script, /NATIONAL_BOROUGH_SWEEPS/, "front end must run nationwide borough buyer sweeps");
assert.match(script, /NATIONAL_BOROUGH_PORTALS/, "front end must expose nationwide borough portal families");
assert.match(script, /National ProContract portal/, "front end must include national ProContract coverage");
assert.match(script, /The Chest - North West/, "front end must include North West borough portal coverage");
assert.match(script, /YORtender coverage - Yorkshire and Humber/, "front end must include Yorkshire and Humber portal coverage");
assert.match(script, /NEPO Open - North East/, "front end must include North East portal coverage");
assert.match(script, /London Tenders Portal/, "front end must include London borough portal coverage");
assert.match(script, /South East Business Portal/, "front end must include South East local authority portal coverage");
assert.match(script, /Kent Business Portal/, "front end must include Kent portal coverage");
assert.match(script, /Supplying the South West/, "front end must include South West local authority portal coverage");
assert.match(script, /Nationwide borough watchlist generated/, "regional mode must explain nationwide borough coverage");
assert.match(script, /Public Contracts Scotland/, "front end must include Scottish procurement watchlist routes");
assert.match(script, /Sell2Wales/, "front end must include Welsh procurement watchlist routes");
assert.match(script, /eTendersNI/, "front end must include Northern Ireland procurement watchlist routes");
assert.match(script, /John Pye trade auctions/, "front end must separate John Pye trade auction searches");
assert.match(script, /runTestLearn/, "front end must run the full test-and-learn cycle");
assert.match(script, /DEFAULT_LEARNING_MODEL/, "front end must maintain a continuous learning model");
assert.match(script, /trackCandidateLearning/, "front end must learn from stock approve/reject decisions");
assert.match(script, /trackDemandLearning/, "front end must learn from bid outcomes");
assert.match(script, /modelConfidence/, "front end must show marketable model health");
assert.match(script, /sourceLearningScore/, "front end must score source reliability continuously");
assert.match(script, /importData/, "front end must import learning data");
assert.match(script, /Source trust/, "front end must expose source-trust scoring");
assert.match(script, /fetchStockEvidenceForTender/, "front end must fetch stock evidence for selected opportunities");
assert.match(script, /stockEvidenceRecordForTender/, "front end must fold auction evidence into opportunity projections");
assert.match(script, /renderStockEvidencePanel/, "front end must display parsed stock evidence and warnings");
assert.match(script, /GOODS_SIGNAL_TERMS/, "front end must score goods signals");
assert.match(script, /SERVICE_RISK_TERMS/, "front end must score service-heavy risk");
assert.match(script, /goodsScore/, "front end must show goods-fit scoring");
assert.match(script, /opportunityUnitValue/, "front end must convert contract value into per-unit stock value");
assert.match(script, /recordMeetsDeadline/, "front end must check stock timing against submission deadline");
assert.match(script, /stockProjectionForTender/, "front end must project stock coverage for each opportunity");
assert.match(script, /opportunityBoardScore/, "front end must rank opportunities by stock and economics viability");
assert.match(script, /startupRouteProfile/, "front end must score startup acquisition routes");
assert.match(script, /STARTUP_ANCHOR_MIN/, "front end must score anchor contract size");
assert.match(script, /Acquisition fit/, "opportunity details must show acquisition fit");
assert.match(script, /Stock available before submission/, "bid readiness must include deadline-based stock coverage");
assert.match(script, /Draft response - executive summary/, "bid pack must draft the executive response");
assert.match(script, /Likely buyer requirements to evidence/, "bid pack must spell out application evidence requirements");
assert.doesNotMatch(script, /buyer request before purchase review/i, "dashboard must not instruct users to work from old saved-buyer wording");
assert.ok(script.includes("source=${encodeURIComponent(settings.source)}"), "front end must pass the selected live source to the API");
assert.ok(script.includes("valueCap=${encodeURIComponent(settings.valueCap)}"), "front end must pass the starter cap to the API");

assert.match(worker, /CONTRACTS_FINDER_RESULTS_URL/, "manual-deploy worker must fetch Contracts Finder");
assert.match(worker, /CONTRACTS_FINDER_API_URL/, "manual-deploy worker must use the official Contracts Finder JSON API");
assert.match(worker, /AUCTION_STOCK_SOURCES/, "manual-deploy worker must expose auction stock source search routes");
assert.match(worker, /handleStockSearch/, "manual-deploy worker must expose stock evidence search API");
assert.match(worker, /John Pye trade auctions/, "manual-deploy worker must include John Pye trade stock route");
assert.match(worker, /John Pye Trade latest stock/, "manual-deploy worker must include John Pye Trade latest-stock route");
assert.match(worker, /procurementRegion/, "manual-deploy worker must normalise UK-wide procurement searches");
assert.match(worker, /johnpyetrade\.co\.uk\/product-category\/uncategorized/, "manual-deploy worker must use the John Pye Trade latest-stock category");
assert.match(worker, /parseJohnPyeTradeCandidates/, "manual-deploy worker must parse John Pye Trade product cards");
assert.match(worker, /trade-price-plus-buyer-premium/, "manual-deploy worker must expose trade price plus buyer premium confidence");
assert.match(worker, /DEFAULT_ACQUISITION_KEYWORDS/, "worker must default to acquisition-focused procurement searches");
assert.match(worker, /parseContractsFinderResults/, "manual-deploy worker must parse Contracts Finder results");
assert.match(worker, /www\.contractsfinder\.service\.gov\.uk/, "detail loader must allow Contracts Finder notice URLs");
assert.match(worker, /agent\.rentalreadyappliances\.com/, "worker must route the agent subdomain to the sourcing dashboard");
assert.match(worker, /sourcing\.rentalreadyappliances\.com/, "worker must route the standalone sourcing subdomain to the sourcing dashboard");
assert.match(worker, /sourcing-dashboard\.html/, "agent subdomain root must serve the sourcing dashboard");

const stockSearch = await readFile("dist/functions/api/stock-search.js", "utf8");
const tenderSearch = await readFile("dist/functions/api/tenders.js", "utf8");
assert.match(stockSearch, /AUCTION_STOCK_SOURCES/, "Pages function must include auction source matrix");
assert.match(stockSearch, /parseAuctionCandidates/, "Pages function must parse stock candidate evidence");
assert.match(stockSearch, /John Pye Trade latest stock/, "Pages function must include John Pye Trade latest-stock route");
assert.match(stockSearch, /parseJohnPyeTradeCandidates/, "Pages function must parse John Pye Trade product cards");
assert.match(stockSearch, /manual verification route/, "Pages function must distinguish manual verification routes");
assert.match(tenderSearch, /procurementRegion/, "Pages tender function must normalise UK-wide procurement searches");

const agentSource = await readFile("agent/sourcing-dashboard.js", "utf8");
assert.match(agentSource, /opportunityRecords/, "agent source must maintain saved opportunity records");
assert.match(agentSource, /syncOpportunityRecords/, "agent source must sync saved opportunity records from demand and stock state");
assert.match(agentSource, /filteredOpportunityRecords/, "agent source must filter saved opportunity records for review");
assert.match(agentSource, /recordReadinessGates/, "agent source must explain opportunity bid-readiness gates");
assert.match(agentSource, /exportOpportunityRecord/, "agent source must export individual opportunity records");
assert.match(agentSource, /rentalready_sourcing_active_opportunity_record/, "agent source must persist the active opportunity record");
assert.match(agentSource, /bidPackageData/, "agent source must create structured bid package data");
assert.match(agentSource, /renderBidPackageWorkspace/, "agent source must render a structured bid package workspace");
assert.match(agentSource, /exportActiveBidPackageJson/, "agent source must export bid package JSON evidence");
assert.match(agentSource, /dailyBidReportData/, "agent source must create daily bid report data");
assert.match(agentSource, /exportDailyBidReportJson/, "agent source must export daily bid report JSON");

const agentHtml = await readFile("agent/sourcing-dashboard.html", "utf8");
assert.match(agentHtml, /opportunityRecordFilter/, "agent dashboard must expose opportunity record filters");
assert.match(agentHtml, /opportunityRecordDetail/, "agent dashboard must expose opportunity record detail review");
assert.match(agentHtml, /sourcing-dashboard\.js\?v=20260610a/, "agent dashboard must reference the latest sourcing-dashboard asset version");

await readFile("website/index.html", "utf8");
await readFile("shared/cloudflare/_worker.js", "utf8");

console.log("Sourcing contract dashboard verification passed.");
